apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    env: dev
spec:
  selector:
      app: kibana
  ports:
    - protocol: TCP
      port: 5601
      nodePort: 32601
  type: NodePort